const EVENTS = {
  LOGIN_SUCCESS: 'CORE:LOGIN:SUCCESS',
  LOGOUT_SUCCESS: 'CORE:LOGOUT:SUCCESS',

  USER_RESET: 'CORE:USER:RESET',
  USER_SET: 'CORE:USER:SET',
  USER_CHANGED: 'CORE:USER:CHANGED',
};

export default EVENTS;
